# Generated by Django 5.0.4 on 2024-11-18 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventgallery',
            name='img',
        ),
        migrations.AddField(
            model_name='eventgallery',
            name='image_url',
            field=models.URLField(blank=True, default='https://eduma.thimpress.com/wp-content/uploads/2022/07/thumnail-cate-7-170x170.png', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eventgallery',
            name='local_image',
            field=models.ImageField(blank=True, null=True, upload_to='event_gallery_images/'),
        ),
    ]
